"""empty message

Revision ID: 3290e7d1e6b4
Revises: 1f0f472c5da1
Create Date: 2022-05-27 23:15:25.771863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3290e7d1e6b4'
down_revision = '1f0f472c5da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('private_messages', 'user_from',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('private_messages', 'user_to',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('private_messages', 'user_to',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('private_messages', 'user_from',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
