"""empty message

Revision ID: a5b1ccbfaeec
Revises: 
Create Date: 2022-05-30 11:58:19.525224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5b1ccbfaeec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('channels', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('username', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('channels', 'user_id')
    # ### end Alembic commands ###
