"""empty message

Revision ID: f239ff55f138
Revises: 698dc70a2262
Create Date: 2022-05-28 03:24:12.893955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f239ff55f138'
down_revision = '698dc70a2262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_messages', sa.Column('username_to', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('private_messages', 'username_to')
    # ### end Alembic commands ###
